spring.application.name=gerenciador-campeonatos

# 1. Configuração da conexão com o banco SQLite
spring.datasource.url=jdbc:sqlite:campeonatos.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# 2. Configuração do comportamento do Hibernate (JPA)
spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true